spring:
  cloud:
    gateway:
      routes:
        - id: f2d-user-authentication
          uri: lb://F2D-USER-AUTHENTICATION
          predicates:
            - Path=/auth/**

        - id: f2d-group-builder
          uri: lb://F2D-GROUP-BUILDER
          predicates:
            - Path=/groups/**
          filters:
            - AuthenticationFilter

        - id: f2d-event-planner
          uri: lb://F2D-EVENT-PLANNER
          predicates:
            - Path=/events/**
          filters:
            - AuthenticationFilter


  application:
    name: F2D-API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://192.168.1.54:8761/eureka/

server:
  port: 9001